version: '{build}'
skip_tags: true
clone_depth: 10
services:
  - postgresql
branches:
  only:
    - master
  except:
    - gh-pages
os: Windows Server 2012
install:
  - cmd: SET PATH=C:\Ruby23-x64\bin;%PATH%
  - cmd: ruby --version
  - cmd: git --version
  - cmd: java -version
  - cmd: mvn --version
  - cmd: PATH=C:\Program Files\PostgreSQL\9.6\bin\;%PATH%
  - cmd: psql --version
build_script:
  - bundle update
  - bundle install
test_script:
  - bundle exec rake
cache:
  - C:\Ruby200\bin -> pgtk.gemspec
  - C:\Ruby200\lib\ruby\gems\2.0.0 -> pgtk.gemspec
